name: python script run
on: push

jobs:
    hello:
        runs-on: ubuntu-latest

        steps:
        - name: clone repo
          uses: actions/checkout@v4

        steps:
        - name: setup python
          uses: action/setup-python@v4
          with:
              python-version: '3.10'

        - name: python run
          uses: python hellow.py
